# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Official full name of the Consultant firm', max_length=100)),
                ('short_name', models.CharField(help_text='Short common name of the Consultant firm', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description of the Consultant firm (Optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Official full name of the Contractor firm', max_length=100)),
                ('short_name', models.CharField(help_text='Short common name of the Contractor firm', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description of the Contractor firm (Optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(help_text='Official full name of the Employer', max_length=100)),
                ('full_name', models.CharField(help_text='Official full name of the construction project', max_length=100)),
                ('short_name', models.CharField(help_text='Short common name of the construction project', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description of the construction project (Optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Consultant')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Contractor')),
            ],
        ),
    ]
