# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_project_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.AddField(
            model_name='contractor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
