# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20171028_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='approved_letter',
            field=models.CharField(blank=True, help_text='Ref. No. for the approval letter. (Optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='submitted_letter',
            field=models.CharField(blank=True, help_text='Ref. No. for the submission letter. (Optional)', max_length=100, null=True),
        ),
    ]
