# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20171029_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='recieved_letter',
            field=models.CharField(blank=True, help_text='Ref. No. for the recieved letter. (Optional)', max_length=100, null=True),
        ),
    ]
