# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20171031_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='approved_letter',
            field=models.CharField(blank=True, help_text='Ref. No. for the approval or rejection letter.', max_length=100, null=True, verbose_name='Ref. No. for approval/rejection letter (Optional)'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='recieved_letter',
            field=models.CharField(blank=True, help_text='Ref. No. for the letter containing the order recieved.', max_length=100, null=True, verbose_name='Ref. No. for recieved Order (Optional)'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='submitted_letter',
            field=models.CharField(blank=True, help_text='Ref. No. for the submission letter of the variation.', max_length=100, null=True, verbose_name='Ref. No. for submission letter (Optional)'),
        ),
    ]
