# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20171031_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the Time Extension Claim', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description about the time extension and claimant arguments. (Optional)', null=True)),
                ('submitted_date', models.DateField(blank=True, help_text='Submitted date of the time extension request. (Use yyyy-mm-dd format)', null=True)),
                ('submitted_letter', models.CharField(blank=True, help_text='Ref. No. for the submission letter of the time extension request.', max_length=100, null=True, verbose_name='Ref. No. for submission letter (Optional)')),
                ('submitted_amount', models.IntegerField(help_text='Submitted amount in calendar days', verbose_name='Requested Amount in Calendar Days')),
                ('approved_date', models.DateField(blank=True, help_text='Approved date of the time extension request. (Use yyyy-mm-dd format)', null=True, verbose_name='Approved/Rejected Date')),
                ('approved_letter', models.CharField(blank=True, help_text='Ref. No. for the approval or rejection letter.', max_length=100, null=True, verbose_name='Ref. No. for approval/rejection letter (Optional)')),
                ('approved_amount', models.IntegerField(blank=True, help_text='Approved amount in calendar days', null=True, verbose_name='Approved Amount in Calendar Days')),
                ('remark', models.TextField(blank=True, help_text='Short helpfull remarks or notes regarding the current status. (Optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Status')),
            ],
        ),
        migrations.AlterField(
            model_name='variation',
            name='remark',
            field=models.TextField(blank=True, help_text='Short helpfull remarks or notes regarding the current status. (Optional)', null=True),
        ),
    ]
