# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20171101_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='number',
            field=models.IntegerField(default=1, help_text='Time claim number'),
            preserve_default=False,
        ),
    ]
