# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20171102_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimstatus',
            name='short_tile',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='short_tile',
            field=models.CharField(default='blank', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variationstatus',
            name='short_tile',
            field=models.CharField(default='blank', max_length=30),
            preserve_default=False,
        ),
    ]
