# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20171102_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimstatus',
            old_name='short_tile',
            new_name='short_title',
        ),
        migrations.RenameField(
            model_name='projectstatus',
            old_name='short_tile',
            new_name='short_title',
        ),
        migrations.RenameField(
            model_name='variationstatus',
            old_name='short_tile',
            new_name='short_title',
        ),
    ]
