# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_auto_20171103_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full official name of the bank or insurance provider firm', max_length=100)),
                ('short_name', models.CharField(help_text='Short (unofficial) commonly used name of the bank or insurance provider firm', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short optional description about the firm', null=True, verbose_name='Short description (optional)')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Insurance amount in ETB', max_digits=16, null=True)),
                ('start_date', models.DateField(help_text='Starting date of this insurance. (Use yyyy-mm-dd format)')),
                ('period', models.IntegerField(help_text='Number of calendar days covered by the insurance')),
                ('end_date', models.DateField(blank=True, help_text='Expiration date of this insurance. (Use yyyy-mm-dd format)', null=True, verbose_name='Expiration date')),
                ('issue_number', models.IntegerField(blank=True, help_text='If unsure, please leave it blank', null=True, verbose_name='Number of revision')),
                ('description', models.TextField(blank=True, help_text='Optional notes or remarks regarding the insruance', null=True, verbose_name='Note (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('short_title', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('group', models.IntegerField(blank=True, help_text='To group different status with different level, give them the same group number', null=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the status meaning. (Optional)', null=True)),
            ],
            options={
                'verbose_name_plural': 'Insurance Status',
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Type of Insurance Bong Guranttee. Example: Advance bond guranttee, Performance bond guranttee etc..', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Short Bio')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Contractor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='claimstatus',
            name='group',
            field=models.IntegerField(blank=True, help_text='To group different status with different level, give them the same group number', null=True),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='group',
            field=models.IntegerField(blank=True, help_text='To group different status with different level, give them the same group number', null=True),
        ),
        migrations.AddField(
            model_name='variationstatus',
            name='group',
            field=models.IntegerField(blank=True, help_text='To group different status with different level, give them the same group number', null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.InsuranceType'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.InsuranceStatus'),
        ),
    ]
