# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20171109_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project contract amount in ETB', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='period',
            field=models.IntegerField(blank=True, help_text='Project life time in calendar days', null=True, verbose_name='Contract Period'),
        ),
        migrations.AlterField(
            model_name='project',
            name='commencement_date',
            field=models.DateField(blank=True, help_text='User yyyy-mm-dd format', null=True, verbose_name='Commenecment Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='signing_date',
            field=models.DateField(blank=True, help_text='User yyyy-mm-dd format', null=True, verbose_name='Agreement Signing Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_handover',
            field=models.DateField(blank=True, help_text='User yyyy-mm-dd format', null=True, verbose_name='Site Handover Date'),
        ),
    ]
