# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20171110_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='mobilzation_period',
        ),
    ]
