# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Contractor'),
        ),
    ]
