# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_project_mobilzation_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, help_text='User yyyy-mm-dd format', null=True, verbose_name='Intended Completion Date'),
        ),
    ]
