# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20171107_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full official name of the bank or insurance provider firm', max_length=100)),
                ('short_name', models.CharField(help_text='Short (unofficial) commonly used name of the bank or insurance provider firm', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short optional description about the firm', null=True, verbose_name='Short description (optional)')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Insurance amount in ETB', max_digits=16, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Starting date of this insurance. (Use yyyy-mm-dd format)', null=True)),
                ('period', models.IntegerField(blank=True, help_text='Number of calendar days covered by the insurance', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional notes or remarks regarding the insruance', null=True, verbose_name='Note (optional)')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('short_title', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('group', models.IntegerField(blank=True, help_text='To group different status with different level, give them the same group number', null=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the status meaning. (Optional)', null=True)),
            ],
            options={
                'verbose_name_plural': 'Insurance Status',
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Type of Insurance Bong Guranttee. Example: Advance bond guranttee, Performance bond guranttee etc..', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.InsuranceType'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.InsuranceStatus'),
        ),
    ]
