# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20171113_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='recieved_date',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='recieved_letter',
        ),
        migrations.AddField(
            model_name='variation',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Received date of the variation or work order. (Use yyyy-mm-dd format)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='received_letter',
            field=models.CharField(blank=True, help_text='Ref. No. for the letter containing the order recieved.', max_length=100, null=True, verbose_name='Ref. No. for received Order (Optional)'),
        ),
    ]
