# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_insurance_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='issue_number',
            field=models.IntegerField(blank=True, help_text='If unsure, please leave it blank', null=True, verbose_name='Number of revision'),
        ),
    ]
