# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20171113_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='number',
        ),
    ]
