# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_insurance_issue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
