# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20171114_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Package title')),
                ('level', models.IntegerField(verbose_name='Package level')),
                ('group', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Package duration in days')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Package price')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
