# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_projects',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max number of projects allowed'),
        ),
        migrations.AddField(
            model_name='package',
            name='max_users',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max number of users allowed'),
        ),
    ]
