# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='contractor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Contractor'),
        ),
    ]
